# Generated by Django 5.0.1 on 2024-05-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_amount',
        ),
    ]
